-- Expand curated ticker universe (Markets browse, cap filters, grading metadata).

insert into tickers (symbol, name, sector, exchange, timezone) values
  ('BRK-B', 'Berkshire Hathaway', 'Financials', 'NYSE', 'America/New_York'),
  ('LLY', 'Eli Lilly', 'Healthcare', 'NYSE', 'America/New_York'),
  ('AVGO', 'Broadcom', 'Semiconductors', 'NASDAQ', 'America/New_York'),
  ('V', 'Visa', 'Financials', 'NYSE', 'America/New_York'),
  ('UNH', 'UnitedHealth', 'Healthcare', 'NYSE', 'America/New_York'),
  ('MA', 'Mastercard', 'Financials', 'NYSE', 'America/New_York'),
  ('COST', 'Costco', 'Consumer', 'NASDAQ', 'America/New_York'),
  ('HD', 'Home Depot', 'Consumer', 'NYSE', 'America/New_York'),
  ('PG', 'Procter & Gamble', 'Consumer', 'NYSE', 'America/New_York'),
  ('JNJ', 'Johnson & Johnson', 'Healthcare', 'NYSE', 'America/New_York'),
  ('NFLX', 'Netflix', 'Internet', 'NASDAQ', 'America/New_York'),
  ('CRM', 'Salesforce', 'Software', 'NYSE', 'America/New_York'),
  ('ORCL', 'Oracle', 'Software', 'NYSE', 'America/New_York'),
  ('BAC', 'Bank of America', 'Financials', 'NYSE', 'America/New_York'),
  ('KO', 'Coca-Cola', 'Consumer', 'NYSE', 'America/New_York'),
  ('MRK', 'Merck', 'Healthcare', 'NYSE', 'America/New_York'),
  ('CVX', 'Chevron', 'Energy', 'NYSE', 'America/New_York'),
  ('PEP', 'PepsiCo', 'Consumer', 'NASDAQ', 'America/New_York'),
  ('TMO', 'Thermo Fisher', 'Healthcare', 'NYSE', 'America/New_York'),
  ('LIN', 'Linde', 'Materials', 'NASDAQ', 'America/New_York'),
  ('ACN', 'Accenture', 'Software', 'NYSE', 'America/New_York'),
  ('MCD', 'McDonald''s', 'Consumer', 'NYSE', 'America/New_York'),
  ('CSCO', 'Cisco', 'Hardware', 'NASDAQ', 'America/New_York'),
  ('ADBE', 'Adobe', 'Software', 'NASDAQ', 'America/New_York'),
  ('DIS', 'Disney', 'Media', 'NYSE', 'America/New_York'),
  ('INTU', 'Intuit', 'Software', 'NASDAQ', 'America/New_York'),
  ('QCOM', 'Qualcomm', 'Semiconductors', 'NASDAQ', 'America/New_York'),
  ('TXN', 'Texas Instruments', 'Semiconductors', 'NASDAQ', 'America/New_York'),
  ('AMAT', 'Applied Materials', 'Semiconductors', 'NASDAQ', 'America/New_York'),
  ('GE', 'GE Aerospace', 'Industrials', 'NYSE', 'America/New_York'),
  ('IBM', 'IBM', 'Software', 'NYSE', 'America/New_York'),
  ('NOW', 'ServiceNow', 'Software', 'NYSE', 'America/New_York'),
  ('CAT', 'Caterpillar', 'Industrials', 'NYSE', 'America/New_York'),
  ('UBER', 'Uber', 'Internet', 'NYSE', 'America/New_York'),
  ('PFE', 'Pfizer', 'Healthcare', 'NYSE', 'America/New_York'),
  ('AMGN', 'Amgen', 'Healthcare', 'NASDAQ', 'America/New_York'),
  ('HON', 'Honeywell', 'Industrials', 'NASDAQ', 'America/New_York'),
  ('BKNG', 'Booking Holdings', 'Internet', 'NASDAQ', 'America/New_York'),
  ('BLK', 'BlackRock', 'Financials', 'NYSE', 'America/New_York'),
  ('GS', 'Goldman Sachs', 'Financials', 'NYSE', 'America/New_York'),
  ('MU', 'Micron', 'Semiconductors', 'NASDAQ', 'America/New_York'),
  ('LRCX', 'Lam Research', 'Semiconductors', 'NASDAQ', 'America/New_York'),
  ('PANW', 'Palo Alto Networks', 'Software', 'NASDAQ', 'America/New_York'),
  ('SNOW', 'Snowflake', 'Software', 'NYSE', 'America/New_York'),
  ('NET', 'Cloudflare', 'Software', 'NYSE', 'America/New_York'),
  ('SOFI', 'SoFi', 'Financials', 'NASDAQ', 'America/New_York'),
  ('RIVN', 'Rivian', 'Autos', 'NASDAQ', 'America/New_York'),
  ('BA', 'Boeing', 'Industrials', 'NYSE', 'America/New_York'),
  ('WMT', 'Walmart', 'Consumer', 'NYSE', 'America/New_York')
on conflict (symbol) do update set
  name = excluded.name,
  sector = excluded.sector,
  exchange = excluded.exchange,
  updated_at = now();
